### ISSUE TITLE
Using CC-BY-SA-4.0 texture in video: How to comply with license? 

### ISSUE THREAD

**Issue by skys-mission** [jasonjgardner/jg-rtx#256]
Quick question about your CC-BY-SA-4.0 texture:

Can I use it in a non-commercial video on platforms like YouTube?

The issue:

Can't release the whole video as CC-BY-SA-4.0 (other elements aren't CC-BY-SA).
Platform terms don't align with CC-BY-SA-4.0.
Might not be able to add links in description due to platform restrictions.
What I can do:

Credit you in the video's end credits
Mention where to find the original work
Note it's used under CC-BY-SA-4.0
Is this okay? Any other suggestions?

Thanks!

**Comment by jasonjgardner** [comment]
I appreciate you checking. Thanks! Yes, go right ahead if you'd like to credit me somehow.
