### ISSUE TITLE
Duplicate tufted grass, one without an alpha channel, and others

### ISSUE THREAD

**Issue by erich666** [jasonjgardner/jg-rtx#4]
**Wha happen?**
Here's a texture that doesn't have an alpha channel: https://github.com/jasonjgardner/jg-rtx/blob/master/assets/blocks/dirt/grass-tuft.png

Here's the same texture, in a different directory, with alpha: https://github.com/jasonjgardner/jg-rtx/blob/master/assets/blocks/grass_block/grass-tuft.png

I suggest doing as I do: delete the grass-tuft*.png files in the "dirt" directory. Bonus: more storage!

I work on Mineways and am adding support for reading jg-rtx PBR files and exporting them for use with Pixar's USD format. Here's a taste of that:

![Jg-rtx](https://user-images.githubusercontent.com/803995/101702570-1e4b2280-3a4f-11eb-9171-e69fee91b4a6.png)

If you're interested, my texture processing programs turn up a number of other duplicates and problems:

DUP WARNING: Duplicate file ignored.
  File 'green_glazed_terracotta.png' is a different name for the same texture 'glazed_terracotta_green.png'.
DUP WARNING: Duplicate file ignored.
  File 'green_glazed_terracotta_mer.png' is a different name for the same texture 'glazed_terracotta_green_mer.png'.
DUP WARNING: Duplicate file ignored.
  File 'green_glazed_terracotta_normal.png' is a different name for the same texture 'glazed_terracotta_green_normal.png'.
DUP WARNING: Duplicate file ignored.
  File 'coarse_dirt.png' in directory 'jg-rtx-master\assets\blocks\dirt\' is in a different location for the same texture 'coarse_dirt.png' in 'jg-rtx-master\assets\blocks\coarse_dirt\'.
DUP WARNING: Duplicate file ignored.
  File 'coarse_dirt_mer.png' in directory 'jg-rtx-master\assets\blocks\dirt\' is in a different location for the same texture 'coarse_dirt_mer.png' in 'jg-rtx-master\assets\blocks\coarse_dirt\'.
DUP WARNING: Duplicate file ignored.
  File 'coarse_dirt_normal.png' in directory 'jg-rtx-master\assets\blocks\dirt\' is in a different location for the same texture 'coarse_dirt_normal.png' in 'jg-rtx-master\assets\blocks\coarse_dirt\'.
  
WARNING: Image 'flower_pot_normal.png' was not used because it seems to be a flat heightfield, no changes detected.
WARNING: Image 'glazed_terracotta_black_normal.png' was not used because it seems to be a flat heightfield, no changes detected.

WARNING: The file 'packed_ce.png' is not recognized and so is not used.
WARNING: The file 'packed_ce_mer.png' is not recognized and so is not used.
WARNING: The file 'packed_ce_normal.png' is not recognized and so is not used.

I expect you meant "packed_ice"

**Comment by jasonjgardner** [comment]
Thanks for the input! I've decided to remove the `assets` directory from version control. It contained files that are not essential for forking or distribution. All the good stuff, like Substance 3D files, had been excluded via [.gitignore](https://github.com/jasonjgardner/jg-rtx/blob/master/.gitignore) anyway.

Mineways is an awesome project and I'm glad I could contribute to it in some fashion!
