### ISSUE TITLE
0.11.0 textures flagged by Mineways' TileMaker

### ISSUE THREAD

**Issue by erich666** [jasonjgardner/jg-rtx#7]
**Wha happen?**

Here are the warnings generated by TileMaker:

RGB MISSING WARNING: File 'rail_normal_normal.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'rail_normal_m.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'rail_normal_r.png' exists but there is no corresponding color file.
RGB MISSING WARNING: File 'rail_detector_powered_m.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'rail_detector_powered_e.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'rail_detector_powered_r.png' exists but there is no corresponding color file.
RGB MISSING WARNING: File 'prismarine_rough_normal.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'prismarine_rough_r.png' exists but there is no corresponding color file.
RGB MISSING WARNING: File 'soul_torch_normal.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'soul_torch_m.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'soul_torch_e.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'soul_torch_r.png' exists but there is no corresponding color file.
TileMaker summary: 1308 relevant PNG files discovered and 1308 of these were used.

I should also mention that "grass_side.png" is what I would call "grass_side_overlay.png" (it's what vanilla Java Minecraft calls it), and "grass_side_carried.png" is one that I rename to be "grass_side.png". Anyway, I think that's my burden to bear, as Bedrock Minecraft seems to use this naming convention, too, and you're just following it.

There are a bunch of files I don't recognize or use - should I?

WARNING: The file 'chain1.png' is not recognized and so is not used.
WARNING: The file 'chain1_mer.png' is not recognized and so is not used.
WARNING: The file 'chain1_normal.png' is not recognized and so is not used.
WARNING: The file 'chain2.png' is not recognized and so is not used.
WARNING: The file 'chain2_mer.png' is not recognized and so is not used.
WARNING: The file 'chain2_normal.png' is not recognized and so is not used.
WARNING: The file 'double_plant_fern_carried.png' is not recognized and so is not used.
WARNING: The file 'double_plant_grass_carried.png' is not recognized and so is not used.
WARNING: The file 'fern_carried.png' is not recognized and so is not used.
WARNING: The file 'flower_hydrangea.png' is not recognized and so is not used.
WARNING: The file 'flower_hydrangea_normal.png' is not recognized and so is not used.
WARNING: The file 'flower_lilac.png' is not recognized and so is not used.
WARNING: The file 'flower_lilac_normal.png' is not recognized and so is not used.
WARNING: The file 'grass_carried.png' is not recognized and so is not used.
WARNING: The file 'grass_carried_mer.png' is not recognized and so is not used.
WARNING: The file 'grass_carried_normal.png' is not recognized and so is not used.
WARNING: The file 'grass_side_carried.png' is not recognized and so is not used.
WARNING: The file 'grass_side_carried_mer.png' is not recognized and so is not used.
WARNING: The file 'grass_side_carried_normal.png' is not recognized and so is not used.
WARNING: The file 'leaves_acacia_carried.png' is not recognized and so is not used.
WARNING: The file 'leaves_big_oak_carried.png' is not recognized and so is not used.
WARNING: The file 'leaves_birch_carried.png' is not recognized and so is not used.
WARNING: The file 'leaves_birch_opaque.png' is not recognized and so is not used.
WARNING: The file 'leaves_jungle_carried.png' is not recognized and so is not used.
WARNING: The file 'leaves_jungle_opaque.png' is not recognized and so is not used.
WARNING: The file 'leaves_oak_carried.png' is not recognized and so is not used.
WARNING: The file 'mood_block.png' is not recognized and so is not used.
WARNING: The file 'mood_block_mer.png' is not recognized and so is not used.
WARNING: The file 'mood_block_normal.png' is not recognized and so is not used.
WARNING: The file 'tallgrass_carried.png' is not recognized and so is not used.
WARNING: The file 'vine_carried.png' is not recognized and so is not used.

Most of these I know I can ignore. But, in particular, the flower names are not ones that even Bedrock Minecraft uses, from what I can tell.

**Comment by erich666** [comment]
BTW, I love seeing the new textures! Bookshelves, lots of flowers & plants, fire, trapdoors, on and on.

**Comment by jasonjgardner** [comment]
I've added a folder named `custom` within the `textures/blocks` directory. I'll stick any non-standard texture I create in that "namespace" to try to avoid confusion.

- The `_carried` textures show what the block looks like in the item menu. It's a prerendered version of blocks whose color is affected per biome.
- Chains were added in Minecraft v1.16
- Some of the flower textures are custom-named. I'll move those to the `textures/blocks/custom` directory.

---

I'm not sure about the warnings from TileMaker. Is that related to any problems with JG RTX in ChannelMixer? The naming convention on the missing files (`_m`, `_r`, `_e`) doesn't match what Win10 Minecraft needs. If I'm not mistaken, those missing files would come from ChannelMixer processing the `_mer` files in texture packs...?

---

Unfortunately, raytracing isn't support on entity textures. The RTX Minecraft beta had support for at least boats and chests, but they seem to have dropped it: https://help.minecraft.net/hc/en-us/articles/360042255511-Minecraft-with-Ray-Tracing-Known-Issues-List

**Comment by erich666** [comment]
Thanks for the rundown.

Chains: in the Java edition (which Mineways aims for), there's just a single "chain.png" file with both your 1 and 2 images in a single image. I don't know if you want to support the Java edition directly in this way, but that's the normal texture.

Yes, if you see an error about an _m, _e, or _r file, that's because ChannelMixer rips _mer files into _m/_e/_r.

Interesting that the entities are not supported in RTX. Ah well.

Anyway, running 0.12.0 through my tools, the warnings relevant to you are as before:

RGB MISSING WARNING: File 'rail_detector_powered_m.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'rail_detector_powered_e.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'rail_detector_powered_r.png' exists but there is no corresponding color file.
RGB MISSING WARNING: File 'prismarine_rough_normal.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'prismarine_rough_r.png' exists but there is no corresponding color file.
RGB MISSING WARNING: File 'soul_torch_normal.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'soul_torch_m.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'soul_torch_e.png' exists but there is no corresponding color file.
  and RGB MISSING WARNING: File 'soul_torch_r.png' exists but there is no corresponding color file.

I'll cheat by copying rail_detector.png to rail_detector_powered.png to avoid the first set of warnings. I leave the other two to you.

Whatever the case, the plants are looking good! Here's a 0.12.0 rendering:

![image](https://user-images.githubusercontent.com/803995/107987631-5a918680-6f9c-11eb-9bac-89dc9d5f1151.png)

**Comment by jasonjgardner** [comment]
I'm going to close this issue since it's for an older release. One more note on the entity textures: Although they won't have raytracing features, I still plan on creating some entity textures. Beds, chests, boats, maybe some mobs, etc.
